[package]
name = "ade-workbench-host"
version = "0.0.1"
edition = "2021"

[features]
host = []  # enable host handlers

[dependencies]
tauri = { version = "1", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
